DROP TABLE IF EXISTS films;
CREATE TABLE IF NOT EXISTS films(
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    genre VARCHAR(255) NOT NULL,
    release_year INTEGER NOT NULL,
    score INTEGER NOT NULL,
);